Add alerts
TheCacophonyProject/cacophony-api pull request #333
Opened 2020-12-01 22:53 UTC by gferraro

2020-12-09 01:04 UTC, hardiesoft requested changes

2020-12-09 01:04 UTC, hardiesoft commented on emailUtil.ts
> +  html: string,
Do we need a text only representation of the email too, or does nodemailer generate one automatically from the html version?

2020-12-09 01:04 UTC, hardiesoft commented on models/Alert.ts
> +  conditions: any;
Conditions should be `AlertCondition[]` rather than `any`, right?

2020-12-09 01:56 UTC, gferraro commented on models/Event.ts
> +    dateTime: Date;
Chanted to pass in a date

2020-12-13 20:20 UTC, hardiesoft commented on report-service-errors.ts
> +  let html = `Service Errors ${startDate.format(
Maybe rename these `html` variables?

2020-12-13 20:41 UTC, hardiesoft approved these changes
Looks good to me, thanks for all the work on this!

2020-12-13 21:56 UTC, merged