Alert on finished
TheCacophonyProject/cacophony-api pull request #395
Opened 2021-07-07 02:49 UTC by gferraro

Only send alerts when a recording has come from analyse state and is finished
User the visit logic to get a tag for the whole recording and only alert on ai master tag of this
Also added cypress tests
Add alert in fileprocessing api if we upload videos into finished state (good for testing with)

2021-07-19 22:33 UTC, hardiesoft requested changes

2021-07-19 22:33 UTC, hardiesoft commented on api/V1/recordingUtil.ts
> +  const recording = (await models.Recording.getForAdmin(recID)) as any;
As discussed, not sure that having the `getForAdmin` abstraction is worthwhile until we have more consumers of that functionality - probably better to just inline the logic here.

2021-07-19 22:33 UTC, hardiesoft commented on api/V1/recordingUtil.ts
> +  const alerts = await (models.Alert as AlertStatic).getActiveAlerts(
It seems like it would be much less work to check for active alerts at the top of this function, and exit early if there are no alerts?

2021-07-19 22:33 UTC, hardiesoft commented on test-cypress/cypress/commands/api/recording.d.ts
> +  processingState: string;
this should be `string | null` right?

2021-07-19 22:33 UTC, hardiesoft commented on test-cypress/cypress/integration/alerts/animal_alerts.ts
> +  it("Alert is based of visit tag, a recording with 2 possum tags and 1 rat is a possum", () => {
of -> off

2021-07-19 22:59 UTC, gferraro commented on test-cypress/cypress/commands/api/recording.d.ts
> +  processingState: string;
yep

2021-07-20 03:06 UTC, hardiesoft approved these changes

2021-07-20 23:43 UTC, merged